### ISSUE TITLE
Release Roadmap

### ISSUE THREAD

**Issue by ianrathbone** [aliostad/CacheCore#1]
Hello I'm a big fan and user of Cachecow and was wondering whether you have any roadmap for an alpha version of CacheCore?

**Comment by aliostad** [comment]
Hi Ian,

Thank you. It is great to hear you have found it useful.

As I responded in the other thread, I am starting it soon. Plan is to finish by around October time, in line with the release of .NET Standard 2.0.

**Comment by ianrathbone** [comment]
Excellent news and thanks for the great work :+1:

**Comment by nareshpatel** [comment]
Hi Ali, is there any update on CacheCore release timeline?
Thanks

**Comment by aliostad** [comment]
There is a setback and essentially .NET team have messed up System.Net.Http so they are releasing a new client library 5.2.4 which seems to fix problems.

More info [here](https://github.com/aspnet/Mvc/issues/5822#issuecomment-351031889)

**Comment by aliostad** [comment]
Hi all,

The plan has changed and essentially .NET Core will be supported under CacheCow name and this repo will be deleted.

Watch the space on CacheCow, plan is to release first version for ASP.NET Core MVC by mid-April.
